server:
  port: 9097

spring:
  application:
    name: auth-service

jwt:
  secret: ${JWT_SECRET:flpZVEZrUG1ORD01Y2MxInkyP2oiQFFqeTN0TXk4NTk=}
  expiration-time: 36000000
  refresh-expiration-time: 86400000

logging:
  level:
    root: info
    org.springframework.security: info
    org.springframework.web: info
