### POST request to create new citizen
POST http://localhost:9091/api/v2/registration/citizens
Content-Type: application/json

{
  "titles": [
    "PROF"
  ],
  "gender": "MALE",
  "firstName": "John",
  "lastName": "Bauer",
  "birthDate": "1945-01-01",
  "birthPlace": "Nuremberg",
  "email": "example@email.com",
  "phones": [
    {
      "number": "04912345678",
      "PhoneType": "MOBILE"
    }
  ],
  "maritalStatus": "SINGLE",
  "addresses": [
    {
      "type": "MAIN",
      "street": "some street 32",
      "zip": "17500",
      "city": "paris"
    }
  ]
}

> {%
    client.global.set("id", response.body.id)
%}