name: workflow.yml
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  discover-services:
    name: Discover Maven Modules
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set-services.outputs.services }}
    steps:
      - uses: actions/checkout@v4
      - id: set-services
        run: |
          SERVICES=$(find . -mindepth 2 -maxdepth 2 -name "pom.xml" -printf "%h\n" | tr '\n' ',' | sed 's/,$//') 
          echo "Found services: $SERVICES"
          echo "services=$SERVICES" >> $GITHUB_OUTPUT
          

  build-test:
    name: Build & Test ${{ matrix.service }}
    runs-on: ubuntu-latest
    needs: discover-services

    strategy:
      matrix:
        service: ${{ fromJson(format('["{0}"]', join(needs.discover-services.outputs.services, '","'))) }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven

      - name: Build Maven project
        run: mvn -f ${{ matrix.service }}/pom.xml clean package -DskipTests

      - name: Run tests
        run: mvn -f ${{ matrix.service }}/pom.xml test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.service }}
          path: ${{ matrix.service }}/target/surefire-reports/

  docker-build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'

    strategy:
      matrix:
        service: ${{ fromJson(format('["{0}"]', join(needs.discover-services.outputs.services, '","'))) }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for ${{ matrix.service }}
        run: |
          docker build -t ${{ matrix.service }}:${{ github.sha }} ${{ matrix.service }}
